# Generated by Django 3.0.7 on 2020-06-28 23:58

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('custodian', models.CharField(blank=True, help_text='Name of the custodian of this data source.', max_length=256, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='naturemap_source_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='naturemap_source_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='The published scientific name of this taxon.', max_length=512)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4283)),
                ('supra', models.CharField(blank=True, help_text='The supra group of this taxon.', max_length=64, null=True)),
                ('family', models.CharField(blank=True, help_text='The taxonomic family of this taxon.', max_length=64, null=True)),
                ('kingdom', models.CharField(blank=True, help_text='The taxonomic kingdom of this taxon.', max_length=64, null=True)),
                ('conservation_status', models.CharField(blank=True, help_text='The conservation status of this taxon.', max_length=16, null=True)),
                ('vernacular', models.CharField(blank=True, help_text='The common name of this taxon.', max_length=256, null=True)),
                ('collector', models.CharField(help_text='The person(s) who collected/identified this taxon sample.', max_length=256)),
                ('collected_date', models.DateField(blank=True, help_text='Date that this taxon sample was collected.', null=True)),
                ('survey', models.CharField(help_text='The name of the survey during which this taxon sample was collected.', max_length=256)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='naturemap_taxonlocation_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='naturemap_taxonlocation_modified', to=settings.AUTH_USER_MODEL)),
                ('published_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.Name')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='naturemap.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
