# Generated by Django 3.0.7 on 2020-06-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE INDEX ON naturemap_taxonlocation USING GIN (name gin_trgm_ops);'),
    ]
