# Generated by Django 3.0.7 on 2020-06-22 05:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexpressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
