# Generated by Django 3.0.7 on 2020-06-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0003_auto_20200622_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='texpressdata',
            name='row_text',
            field=models.TextField(blank=True, help_text='Document for search', null=True),
        ),
    ]
