# Generated by Django 3.0.7 on 2020-06-24 04:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herbarium', '0005_auto_20200623_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='agent',
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('Collector', 'Collector'), ('Taxonomist', 'Taxonomist'), ('Other', 'Other')], max_length=64),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='A unique name for this organisation.', max_length=256, unique=True)),
                ('email', models.EmailField(blank=True, help_text='A valid email address.', max_length=254, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='herbarium_organisation_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='herbarium_organisation_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agent',
            name='member_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='herbarium.Organisation'),
        ),
    ]
