# Generated by Django 3.0.7 on 2020-06-24 04:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herbarium', '0006_auto_20200624_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='collectingevent',
            old_name='agent',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='determination',
            old_name='agent',
            new_name='person',
        ),
    ]
