# Generated by Django 3.0.7 on 2020-06-24 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herbarium', '0007_auto_20200624_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='herbarium.Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='herbarium.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='herbarium_person_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='herbarium_person_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='A unique name for this person.', max_length=256, unique=True),
        ),
    ]
