# Generated by Django 3.0.7 on 2020-06-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0008_auto_20200624_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='person',
            name='member_of',
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('Primary mail', 'Primary mail'), ('Primary physical', 'Primary physical'), ('Additional mail', 'Additional mail'), ('Additional physical', 'Additional physical'), ('Other', 'Other')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbarium.Address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='herbarium.Organisation'),
        ),
    ]
